### ISSUE TITLE
Including a specific commented section when compiling

### ISSUE THREAD

**Issue by Alekhoff** [Xeverous/filter_spirit#19]
Hey, 

Love this filter generator, its what i have been looking for!

Is there any way to include only some  Highlight block that is normally commented out, but i uncomment them if i need to look for a specific item for one or two maps?

So i dont have to uncomment it, then compile, then comment it out again and compile again when I got what i was looking for.

**Comment by Xeverous** [comment]
Currently, no. This will be solved once the feature of generating multiple filter variants is present. If you have any syntax/semantics idea, post in #7.

Current partial workaround: FS does not generate blocks which would be invalid - so far this only happens when a string condition (class/base type/has explicit mod/has enchantment) has empty list of names. So if you have:

```
# x = ["something", "you", "want", "to", "pick", "up"]
x = []

Class x {
   ...
```
by (un)commenting 1 line you can swap between generating and not generating a set of nested blocks that depends on a string-based condition.

**Comment by Xeverous** [comment]
Do you have any more questions or can this be closed? The actual lacking feature is tracked by #7.

**Comment by Xeverous** [comment]
Agreed to close on a private message.
