### ISSUE TITLE
Prophecies conditions

### ISSUE THREAD

**Issue by Alekhoff** [Xeverous/filter_spirit#22]
**Description and/or example**
Need to add `Prophecy` as a condition that allows strings or arrays in case someone dont want to pull the tier lists based on poe.ninja, but would rather tier them self. Self made tiers can be very useful for SSF where cheap prophecies/uniques/fossil/incubator etc. can be very useful even tho they are not worth a lot in trade league. This matters for all of the stuff that can be pulled automatically via price queries. 

I understand that the price queries are one of the core functions of this tool, but personally as a HCSSF player, they help me very little as i want to tier everything my self as i dont trust the economy and me to have the same value on certain items. 

**Code Example**
This code snippet i took from NeverSink to display how his filter does prophecies
<pre>
	Class Currency
	BaseType "Prophecy"
	Prophecy "A Dishonourable Death" "Fated Connections" "Lost in the Pages" "The Bowstring's Music" "The King's Path" "The Queen's Sacrifice" "Trash to Treasure"
	SetFontSize 45
	SetTextColor 130 25 255 255             # TEXTCOLOR:	 Blessing
	SetBorderColor 130 25 255 255           # BORDERCOLOR:	 Breach
	SetBackgroundColor 255 255 255 255      # BACKGROUND:	 T0 Drop
	PlayAlertSound 6 300                    # DROPSOUND:	 T0 Drop
	PlayEffect Red
	MinimapIcon 0 Red Star
</pre>

If i try the example under, i get a parse error.

<pre>
BaseType "Prophecy"{
        Prophecy ["The Queen's Sacrifice", "Fated Connections", "Trash to Treasure", "The King's Path", "Lost in the Pages"]{
            SetFontSize font_max
            Show
        }

    }
</pre>

**Comment by Xeverous** [comment]
> Self made tiers can be very useful for SSF where cheap prophecies/uniques/fossil/incubator etc. can be very useful even tho they are not worth a lot in trade league.

I have thought earlier of the SSF mode option - basically disable price queries (using them would trigger an error) for the benefit of not having to download data at generation time. This would speed up the generation, but I don't think there is really a need for it now since the ability to load previously downloaded data was added just before first release - reading from disk is faster and in your case the data simply won't be used if there are no queries.

> I understand that the price queries are one of the core functions of this tool, but personally as a HCSSF player, they help me very little

Price queries are semantically equivalent to writing an array in their place. There should be no problem in replacing all of them with fixed data. If you find any interaction that is problematic, report it as a bug. The grammar should be fully composable and not impose artificial requirements.

In case of `Prophecy` condition this is simply another condition that was missed when writing the tool. `BaseType` should work as a temporary workaround. I will add it when I'm back from work.

**Comment by Xeverous** [comment]
Added in 39259f7a7773ecfdcb56d3505883b7ce76d72b3c.
